### PR TITLE
Add curled and dotted underline for diagnostics

### PR DESCRIPTION
**Pull request by epbuennig**
I'm wondering if support for underline styles ([helix#3015](https://github.com/helix-editor/helix/pull/3015), superseded by [helix#4064](https://github.com/helix-editor/helix/pull/4061)) is planned. This would bring the themes in this repo on par with the default themes in terms of diagnostic support.

There are currently 4 underline styles: 
- `curl`
- `dashed`
- `dotted` (docs mention `dot` but that is not correct on [master](https://github.com/helix-editor/helix/blob/ac0fe29867012ba0840ee7c8893b41d976d5ab38/helix-view/src/graphics.rs#L335))
- `double_underline`

These should ideally feel familiar, so the color should match the gutter icon's color, the style should match what other popular editors do.

### Other Editors
Diagnostic differences:
|helix/lsp|intelij-based|vscode|
|---|---|---|
error|error|error|
warning|warning|warning|
info|hint|info|
hint|suggestion|info (different styling)|

#### IntelliJ-based IDEs
|severity|underline type|color|styling|
|---|---|---|---|
|error|`undercurled`|vibrant red| -|
|warning|`undercurled`|soft red| - |
|info|`underdotted`|vibrant cyan|short span, nothing we have control over|
|hint|`undercurled`|soft yellow| - |

#### Visual Studio Code
|severity|underline type|color|styling|
|---|---|---|---|
|error|`undercurled`|vibrant red| - |
|warning|`undercurled`|vibrant yellow| - |
|info|`underdashed`|vibrant cyan|short span, nothing we have control over|
|hint|`underdashed`|soft yellow| - |

Most themes for these editors don't interfere with the default styling of the diagnostics. The changes are simple
```diff
+ "diagnostic.hint" = { underline = { color = <hint>, style = "dotted" } }
+ "diagnostic.info" = { underline = { color = <info>, style = "dotted" } }
+ "diagnostic.warning" = { underline = { color = <warning>, style = "curl" } }
+ "diagnostic.error" = { underline = { color = <error>, style = "curl" } }
```

As well as removing the deprecated option for the fallback style and changing it to curl (same as the default theme):
```diff
- "diagnostic" = { modifiers = ["underlined"] }
+ "diagnostic" = { underline = { style = "line" } }
```

I've tried this with `gruvbox_original_dark_hard` only, but I figure this Is simple enough that it should work for all of them.
It's up to you if prefer curl for all of them or dashed over dotted, I thought the distinction from color only is a bit hard to see, and the dashed underline looked kind of weird to me.

### CODE REVIEW

**Comment by epbuennig** [comment]
Using gruvbox original dark hard in alacritty:
image

Using gruvbox original dark hard in kitty:
image

The same with dashed as reference:
image
image

**Comment by epbuennig** [comment]
I see this on wezterm, are you up to date?
image

**Comment by CptPotato** [comment]
Looks great! Interestingly, I'm using the same wezterm version but the styled underlines don't show up for me:

image

I'll have to check why that happens. Regardless, the changes and visuals look good to me, so unless there's other things you want to address I'd go ahead and merge this.

**Comment by epbuennig** [comment]
Perhaps you're still on helix 22.08, I'm running master because the arch package is always a bit late. So while it is released, it may not be available on your system either.

**Comment by epbuennig** [comment]
If you're ok with dotted over dashed then it's good to merge.

**Comment by CptPotato** [comment]
Thanks!

**Pull request merged**
